### ISSUE TITLE
多个时间段执行设置问题

### ISSUE THREAD

**Issue by nisiyong** [elasticjob/elastic-job-lite#168]
你好，我这边编写自动任务时遇到时间管理的问题。
比如我想在9:00-12:00、15:00-18:00这两个时间段每5分钟执行一次，cron表达式好像不支持多个时间段。
因为旧项目用了cron4j，是可以用“|”来连接多个cron表达式的，elastic-job底层用了quartz，应该可以设置
多个触发器的，但是elastic-job只能配置一个CronTrigger。

**Comment by Lancelothe** [comment]
请问怎么解决呢，有该功能了吗
